spring.application.name=niise-demo
server.port=8005

spring.datasource.url=jdbc:sqlite:niise_local.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Add this fix line
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
